package app.protein.tracker.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// A calm sage-and-teal palette, used when wallpaper colours (Material You) are off or
// not available. There is deliberately no red anywhere in the app.

val LightColors = lightColorScheme(
    primary = Color(0xFF2E6A5C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB3EFDD),
    onPrimaryContainer = Color(0xFF00201A),
    inversePrimary = Color(0xFF97D3C1),
    secondary = Color(0xFF4B635C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCDE8DF),
    onSecondaryContainer = Color(0xFF06201A),
    tertiary = Color(0xFF426278),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC7E7FF),
    onTertiaryContainer = Color(0xFF001E2E),
    background = Color(0xFFF6FAF7),
    onBackground = Color(0xFF171D1B),
    surface = Color(0xFFF6FAF7),
    onSurface = Color(0xFF171D1B),
    surfaceVariant = Color(0xFFDBE5E0),
    onSurfaceVariant = Color(0xFF3F4945),
    surfaceTint = Color(0xFF2E6A5C),
    inverseSurface = Color(0xFF2C3230),
    inverseOnSurface = Color(0xFFECF2EE),
    outline = Color(0xFF6F7975),
    outlineVariant = Color(0xFFBFC9C4),
    surfaceBright = Color(0xFFF6FAF7),
    surfaceDim = Color(0xFFD6DBD8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF0F5F1),
    surfaceContainer = Color(0xFFEAEFEB),
    surfaceContainerHigh = Color(0xFFE4E9E6),
    surfaceContainerHighest = Color(0xFFDFE4E0),
)

val DarkColors = darkColorScheme(
    primary = Color(0xFF97D3C1),
    onPrimary = Color(0xFF00382E),
    primaryContainer = Color(0xFF0F5144),
    onPrimaryContainer = Color(0xFFB3EFDD),
    inversePrimary = Color(0xFF2E6A5C),
    secondary = Color(0xFFB1CCC3),
    onSecondary = Color(0xFF1D352F),
    secondaryContainer = Color(0xFF334B45),
    onSecondaryContainer = Color(0xFFCDE8DF),
    tertiary = Color(0xFFAACBE4),
    onTertiary = Color(0xFF113448),
    tertiaryContainer = Color(0xFF2A4A5F),
    onTertiaryContainer = Color(0xFFC7E7FF),
    background = Color(0xFF0F1513),
    onBackground = Color(0xFFDEE4E0),
    surface = Color(0xFF0F1513),
    onSurface = Color(0xFFDEE4E0),
    surfaceVariant = Color(0xFF3F4945),
    onSurfaceVariant = Color(0xFFBFC9C4),
    surfaceTint = Color(0xFF97D3C1),
    inverseSurface = Color(0xFFDEE4E0),
    inverseOnSurface = Color(0xFF2C3230),
    outline = Color(0xFF89938F),
    outlineVariant = Color(0xFF3F4945),
    surfaceBright = Color(0xFF353B39),
    surfaceDim = Color(0xFF0F1513),
    surfaceContainerLowest = Color(0xFF0A0F0E),
    surfaceContainerLow = Color(0xFF171D1B),
    surfaceContainer = Color(0xFF1B211F),
    surfaceContainerHigh = Color(0xFF252B29),
    surfaceContainerHighest = Color(0xFF303634),
)
